alter table Product drop foreign key FK8pob6ns5y69lmy4wbvc2oc60;
alter table user_command drop foreign key FK2ti1f0t7d3dra98c860pun1x3;
alter table user_command drop foreign key FKsoeerr6rp3fyjcfqwv4f1cwdw;
drop table if exists hibernate_sequence;
drop table if exists Product;
drop table if exists Type;
drop table if exists User;
drop table if exists user_command;
create table hibernate_sequence (next_val bigint);
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table Product (idproduct integer not null, price varchar(255), productname varchar(255), quantity varchar(255), idtype integer, primary key (idproduct));
create table Type (idtype integer not null, typename varchar(255), primary key (idtype));
create table User (iduser integer not null, isAdmin integer not null, lastname varchar(255), password varchar(255), username varchar(255), primary key (iduser));
create table user_command (idcommand integer not null, quantity integer not null, status integer, idproduct integer, iduser integer, primary key (idcommand));
alter table Product add constraint FK8pob6ns5y69lmy4wbvc2oc60 foreign key (idtype) references Type (idtype);
alter table user_command add constraint FK2ti1f0t7d3dra98c860pun1x3 foreign key (idproduct) references Product (idproduct);
alter table user_command add constraint FKsoeerr6rp3fyjcfqwv4f1cwdw foreign key (iduser) references User (iduser);
alter table Product drop foreign key FK8pob6ns5y69lmy4wbvc2oc60;
alter table user_command drop foreign key FK2ti1f0t7d3dra98c860pun1x3;
alter table user_command drop foreign key FKsoeerr6rp3fyjcfqwv4f1cwdw;
drop table if exists hibernate_sequence;
drop table if exists Product;
drop table if exists Type;
drop table if exists User;
drop table if exists user_command;
create table hibernate_sequence (next_val bigint);
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table Product (idproduct integer not null, price varchar(255), productname varchar(255), quantity varchar(255), idtype integer, primary key (idproduct));
create table Type (idtype integer not null, typename varchar(255), primary key (idtype));
create table User (iduser integer not null, isAdmin integer not null, lastname varchar(255), password varchar(255), username varchar(255), primary key (iduser));
create table user_command (idcommand integer not null, quantity integer not null, status integer, idproduct integer, iduser integer, primary key (idcommand));
alter table Product add constraint FK8pob6ns5y69lmy4wbvc2oc60 foreign key (idtype) references Type (idtype);
alter table user_command add constraint FK2ti1f0t7d3dra98c860pun1x3 foreign key (idproduct) references Product (idproduct);
alter table user_command add constraint FKsoeerr6rp3fyjcfqwv4f1cwdw foreign key (iduser) references User (iduser);
